AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 creada desde GitHub Actions

Resources:

  ServerSecurityGroupClase:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso HTTP y SSH

      Tags:
        - Key: Name
          Value: SG-HTTP-Clase-CF

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a

      ImageId: ami-08a6efd148b1f7504

      InstanceType: t3.micro

      SecurityGroupIds:
        - !Ref ServerSecurityGroupClase

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd

          systemctl start httpd
          systemctl enable httpd

          cat <<EOF > /var/www/html/index.html
          <html>
          <body>
            <h1>EC2 desplegada correctamente</h1>
            <h2>Hola desde CloudFormation con GitHub Actions</h2>
          </body>
          </html>
          EOF

      Tags:
        - Key: Name
          Value: EC2-GitHubActions

Outputs:

  InstanceId:
    Description: ID de la instancia EC2
    Value: !Ref MyEC2

  PublicIP:
    Description: IP pública de la instancia
    Value: !GetAtt MyEC2.PublicIp